# Generated by Django 5.1.1 on 2026-02-22 09:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('firstblock', 7)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Текст кнопки', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Ссылка кнопки', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 1), ('button', 5), ('image', 6)]], {})})),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
    ]
