# Generated by Django 5.1.1 on 2026-02-22 10:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nav_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название пункта'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Якорь (например: #hero)'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('anchor', 1)]], {})}, verbose_name='Пункты меню'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Telegram URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vk_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='ВКонтакте URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='WhatsApp URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('firstblock', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: hero, about — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок (имя и профессия)'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок (услуги)', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Ссылка кнопки', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('heading', 1), ('subheading', 2), ('description', 3), ('button_text', 4), ('button_link', 5), ('image', 6)]], {})}),
        ),
    ]
