# Generated by Django 5.1.1 on 2026-02-22 17:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('firstblock', 7), ('diplomas', 12), ('feedback', 15)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: hero, about — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок (имя и профессия)'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок (услуги)', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Ссылка кнопки', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('anchor_id', 0), ('heading', 1), ('subheading', 2), ('description', 3), ('button_text', 4), ('button_link', 5), ('image', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: education — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок раздела', 'required': False}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Дипломы'}), 12: ('wagtail.blocks.StructBlock', [[('anchor_id', 8), ('heading', 9), ('diplomas', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: feedback, contact — используется в меню навигации', 'label': 'ID раздела (якорь)', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 15: ('wagtail.blocks.StructBlock', [[('anchor_id', 13), ('heading', 14)]], {})}),
        ),
    ]
