# Generated by Django 5.1.1 on 2026-02-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='max_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='MAX URL'),
        ),
    ]
