# Generated by Django 5.1.1 on 2026-02-23 10:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homepage_max_url'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('accordion', 4)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержимое', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('contents', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('points', 3)]], {})})),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
            },
            bases=('wagtailcore.page',),
        ),
    ]
